### ISSUE TITLE
Add way to disambiguate multiple tags in feature files

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#79] opened 2023-06-22 13:56 UTC
Hello,

I have already implemented a Cypress Cucumber Test Automation Framework running with all test scenarios each of them have one or more tags. Some Scenarios have the same Ticket Tag because I test them on different languages. On Bamboo I had solved this issue with a language Tag, so therefore I had 2 separate builds running one for each tag/language. Now I want to do the same with the cypress-xray-plugin, but I get a fail when running the command `npx cypress run --env tags="@EN" JIRA_API_TOKEN="PATToken"`  with the error: `Error: Failed to configure Xray uploader: no viable Xray configuration was found or the configuration you provided is not supported.` 

What did I do wrong?

If I leave the tag out I get an error that I have multiple tests with same tag. Also I have an issue with another plugin `cy-verify-downloads ` which works perfectly in open mode.

**Comment by csvtuda** [comment] 2023-06-22 14:12
Hey @alexviz7,

thanks for creating the issue. I don't think I fully understand it yet. Would you mind providing a minimal reproducible example containing your tag configuration?  You don't have to include step definitions or your real steps. I'm just a little bit confused still, especially about the `tags="@EN"` parameter. I assume this is a custom thing for choosing the subset of tags to include in a run? Without the example it's difficult for me to deduce why the plugin would be complaining about identical tags.

---

> Error: Failed to configure Xray uploader: no viable Xray configuration was found or the configuration you provided is not supported

This error indicates that Xray wasn't properly configured. You seem to be using a server instance, which requires the `JIRA_API_TOKEN` environment variable (which you've set up) and the `jira.url` (see [here](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#url)). Can you double check if you've set up the URL?

**Comment by csvtuda** [comment] 2023-06-22 16:51
Yes, thank you very much for the detailed example! I managed to set up a corresponding project myself.

> [`npx cypress run --env tags="@EN" JIRA_API_TOKEN="token"`] has the following error:
Error: Failed to configure Xray uploader: no viable Xray configuration was found or the configuration you provided is not supported.

You've really set up everything properly. I think the issue is that you're separating the environment variables with a space, not a comma: https://docs.cypress.io/guides/guides/environment-variables#Option-4---env

> [`npx cypress run --env JIRA_API_TOKEN="token"`] has the following error:
Multiple issue keys found in tags of scenario "View page footer and header": PRJ-2441, PRJ-2747

Multiple tags are pretty problematic, true. But what should the plugin do? Right now there's no way to tell it which tag to use. In such a situation, the plugin is facing a difficult choice:
- upload the results to the issue of the first tag?
- upload the results to the issue of the last tag?
- upload the results to issues of both tags?

Simply throwing the above error is currently the user-friendliest way, I think. But maybe you've got an alternative solution/proposal? I'm definitely open for it.


Regarding the errors of `cy-verify-downloads`: I'm not quite firm in bundling topics, but have you tried adding `nodepolyfills()` to this bundler as well?
```ts
on('file:preprocessor', async (file) => {
  await syncFeatureFile(file);
  const cucumberPlugin = createBundler({
    plugins: [nodepolyfills(), createEsbuildPlugin(config)],
    //        ^^^^^^^^^^^^^^^
  });
  return cucumberPlugin(file);
});
```
 
This fixed the error for me, although I used a [different polyfill package](https://github.com/elaichenkov/cy-verify-downloads/issues/51) I think (I could not figure out which one you're using).

**Comment by alexviz7** [comment] 2023-06-22 19:06
Wow, thank you it solved the issues with the cy-verify-downloads and the run command with the comma. 
 I still get the error of the multiple tags but the test run nevertheless. 
However I get another issue now after the first feature tested the run stops with status code 405, most likely because i still have the cypress cucumber reporter configured:

```
`Running:  downloadUploadFiles.feature                                                    (1 of 42)
| Cypress Xray Plugin | INFO    | Synchronizing upstream Cucumber tests (cypress\e2e\features\downloadUploadFiles.feature)
| Cypress Xray Plugin | INFO    | Importing cucumber feature files...
| Cypress Xray Plugin | ERROR   | Feature file "[object Object]" invalid, skipping synchronization: AxiosError: Request failed with status code 405


  Download & Upload Files
    √ Download Effective Root Certificate (7801ms)


  1 passing (8s)

[mochawesome] Report JSON saved to C:\Projects\cypress\results\mochawesome_003.json

An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

Error: ENOENT: no such file or directory, open 'C:\Projects\cypress\cucumber-json\cucumber-messages.ndjson'
```

**Comment by csvtuda** [comment] 2023-06-22 20:34
Yeah, the multiple tags found error is not going to disappear, I'm afraid. The plugin just can't decide for you which tag to use.
The only thing I could think of right now is to provide a tag prefix in the configuration. Something like this:

```ts
await configureXrayPlugin({
cucumber: {
  featureFileExtension: '.feature',
  uploadFeatures: true,
  tagPrefix: "PRJ"
},
```

Would this help you? After changing your tags, you would then be able to provide prefixes through `npx run --env CUCUMBER_TAG_PREFIX="PRJ-EN"`.

---

Regarding the upload: I cannot reproduce the error, unfortunately. I don't think the reporter is at fault, it should not influence the plugin. The 405 response is interesting, [Xray's documentation](https://docs.getxray.app/display/XRAY/Importing+Cucumber+Tests+-+REST) states that it only returns the following codes on import:
- 400 BAD_REQUEST
- 401 UNAUTHORIZED
- 500 INTERNAL SERVER ERROR

Can you set `plugin.debug` to `true` in the configuration? This should create JSON files containing request data, such as the URL that was used to import the Cucumber file. It should look something like this in your setting:
```asm
https://devstack.jira.com/rest/raven/latest/import/feature?projectKey=PRJ
```

If this is correct, can you try replacing `latest` with `1.0` in the plugin's source code? 
```asm
https://devstack.jira.com/rest/raven/1.0/import/feature?projectKey=PRJ
```

You can do it directly in the `node_modules` folder. Just change it in the following line in
`node_modules/cypress-xray-plugin/src/client/xray/xrayClientServer.js`:
![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/1709c672-ae31-4dac-a7b2-133da4877517)


Maybe this helps already. Otherwise I would need to add better debugging/logging output, I think.

---

⚠ Do **not** simply copy and paste entire debug payloads here for further analysis, as they *will* contain your credentials! ⚠

**Comment by alexviz7** [comment] 2023-06-23 08:26
Hi I didnt try the debugging( maybe you can explain me where to set it), 
however i managed to **fix the issue** of the stopping test run by **removing the cypress-cucumber json creation** from the package.json:
![2023-06-23 11_18_44-package json - Visual Studio Code  Administrator](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/c4ddfe54-9c43-4fb5-ae62-6c4a8faeeffb)

Now all test scenarios run even if they have same tags.
After the test execution is finished i see following info:
```
| Cypress Xray Plugin | INFO    | Uploading test results to https://devstack.com/jira/projects/PRJ/...
| Cypress Xray Plugin | DEBUG   | Writing POST request data to POST_https_devstack.com_jira_projects_PRJ_rest_raven_latest_api_import_execution_1687507965699_request.json.
| Cypress Xray Plugin | ERROR   | Failed to upload results to Xray: "AxiosError: Request failed with status code 405"
| Cypress Xray Plugin | ERROR   | Complete error logs have been written to "importExecutionResultsError.json"
| Cypress Xray Plugin | WARNING | Execution results import failed. Skipping remaining tasks.
```

**Comment by alexviz7** [comment] 2023-06-23 11:53
Another issue i found out, that when I run the test with tag=EN I have new test tickets created even though all the scenarios have ticket numbers taged on them. Now i have to delete the doublicates from jira.

**Comment by csvtuda** [comment] 2023-06-23 12:14
I'm glad to hear it was just the URL that required changing. 
> Also I found out if a ticket is closed then no result is shown. So I had some old tests that i had closed, now I had to reopen them.

Would you mind elaborating on this problem? I've never had to reopen issues before. Ideally, please provide steps to reproduce the problem.

> Another issue i found out, that when I run the test with tag=EN I have new test tickets created even though all the scenarios have ticket numbers taged on them. Now i have to delete duzen dublicates from jira.

Yes, this is what I was trying to explain earlier in the comments (https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/79#issuecomment-1603005048, https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/79#issuecomment-1603281133). There's just no way currently for the plugin to know which issue you would like to reuse when providing multiple tags. Please consider the proposal I made in the last comment and if it would be an adequate solution for you.

**Comment by csvtuda** [comment] 2023-06-23 14:14
> Could you please check why the cypress cucumber json creation has to be deleted in order that the test run does not stop?

I investigated it. The situation is as follows:
- the `cypress-cucumber-preprocessor` hooks into Cypress's `before:run` event: https://github.com/badeball/cypress-cucumber-preprocessor/blob/c6b40d3397899c75a41be71556f47d41a648f543/lib/add-cucumber-preprocessor-plugin.ts#L90
  - the hook then creates the folders where the report will be written to: https://github.com/badeball/cypress-cucumber-preprocessor/blob/c6b40d3397899c75a41be71556f47d41a648f543/lib/plugin-event-handlers.ts#L178
- the `cypress-xray-plugin` hooks into Cypress's `before:run` event: https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/c2808fb4893a9152d5c5c54d31ed13587ae65c76/plugin.ts#L10

The big issue is that Cypress *does not allow multiple hooks*. The last function that hooks into the event will replace all the other ones: https://github.com/cypress-io/cypress/issues/22428. In your case, the `cypress-xray-plugin` hook won, preventing the `cypress-cucumber-preprocessor` from creating the output directory, resulting in your 
`Error: ENOENT: no such file or directory: 'C:\Projects\cypress\cucumber-json\cucumber-messages.ndjson'` error.

Unless I (or Cypress) come up with a solution to this problem, you will need to decide between:
- the JSON report of the `cypress-cucumber-preprocessor`
- the upload of the `cypress-xray-plugin`

Both at the sime time is not possible. If you want to keep using the `cypress-xray-plugin` without having to delete your JSON configuration, make sure to omit the `cucumber-preprocessor-plugin` event handlers as described here: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/setup/installation/#cucumber-support

---

> This is also an issue for the scenarios with examples (Scenario Outline). When I have 5 examples 5 tickets are created. Can the ticket generation not be stopped in the xray or jira configuration?

This problem was fixed in `v3.3.1`. If *exactly* one tag is configured for a scenario, the examples won't result in superfluous Jira issue creation. However, the plugin does not yet support combining examples into a single data-driven test execution issue (as described [here](https://docs.getxray.app/display/XRAY/Parameterized+Tests#ParameterizedTests-Execution)). I currently don't have the time for such a big undertaking, unfortunately. But it's definitely a necessary feature which will be included in a future version.

Can you check if you're on `v3.3.`1 or above?

**Comment by alexviz7** [comment] 2023-06-23 14:23
> The big issue is that _Cypress does not allow multiple hooks_. The last function that hooks into the event will replace all the other ones: [cypress-io/cypress#22428](https://github.com/cypress-io/cypress/issues/22428). In your case, the `cypress-xray-plugin` hook won, preventing the `cypress-cucumber-preprocessor` from creating the output directory, resulting in your `Error: ENOENT: no such file or directory: 'C:\Projects\cypress\cucumber-json\cucumber-messages.ndjson'` error.
> 
> Unless I (or Cypress) come up with a solution to this problem, you will need to decide between:
> 
>     * the JSON report of the `cypress-cucumber-preprocessor`
> 
>     * the upload of the `cypress-xray-plugin`
> 

Ok thanks, I ll take it in consideration which is more useful for reporting.

> This problem was fixed in `v3.3.1`. If _exactly_ one tag is configured for a scenario, the examples won't result in superfluous Jira issue creation. However, the plugin does not yet support combining examples into a single data-driven test execution issue (as described [here](https://docs.getxray.app/display/XRAY/Parameterized+Tests#ParameterizedTests-Execution)). I currently don't have the time for such a big undertaking, unfortunately. But it's definitely a necessary feature which will be included in a future version.
> 
> Can you check if you're on `v3.3.1` or above?

Yes i have this installed:  `"cypress-xray-plugin": "^3.3.1",`

![2023-06-23 17_08_58-cypress config ts - Visual Studio Code  Administrator](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/e9f640aa-f62d-4a94-ad00-d50045feb7a5)

Also the tagPrefix is not recognized.

**Comment by csvtuda** [comment] 2023-06-23 14:27
> Also the tagPrefix is not recognized.

Yes, the option does not exist yet. It was just something I came up with to discuss with you if that would be a solution to your problem.

**Comment by csvtuda** [comment] 2023-06-23 15:46
The plugin does not retrieve Cucumber step information as of now, unfortunately. It will only upload screenshots/videos and set the corresponding status in Xray.

**Comment by csvtuda** [comment] 2023-06-26 20:45
Thank you for the link, I actually did not know about that. This is very useful and highly interesting. I will report my findings in #87.

I will leave this PR open for some time, so that you can provide more examples whenever you find the time.

Apart from that, I'm sorry that the Cucumber integration isn't as fleshed out as the other parts of the plugin. The plugin was created more or less out of necessity, and Cucumber has not really been the main focus of that project.

**Comment by badeball** [comment] 2023-07-05 13:39
> Unless I (or Cypress) come up with a solution to this problem, you will need to decide between:

This is not true and can be achieved using [cypress-on-fix](https://github.com/bahmutov/cypress-on-fix).

> If you don't want to keep using the `cypress-xray-plugin` without running into errors or deleting your JSON configuration, make sure to omit the `cucumber-preprocessor-plugin` event handlers as described here: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/setup/installation/#cucumber-support. This will reduce the `cucumber-preprocessor-plugin` to running Cucumber tests only. No reports whatsoever will be generated anymore.

This documentation is misleading, for reason mention above.

**Comment by csvtuda** [comment] 2023-07-05 22:27
Thank you @badeball, I did not know about `cypress-on-fix`. I will try it out and adapt the documentation accordingly! Sorry for any inconveniences or headaches the current setup has caused.

**Comment by badeball** [comment] 2023-07-06 07:50
> Sorry for any inconveniences or headaches the current setup has caused.

No inconvenience at all, I just want everyone to have the best experience.

**Comment by alexviz7** [comment] 2023-07-06 09:50
> This is not true and can be achieved using [cypress-on-fix](https://github.com/bahmutov/cypress-on-fix).

So according to this plugin it is possible to create a cucumber report and work with the xray plugin. 
I haven't managed to make it work though.

**Comment by csvtuda** [comment] 2023-08-28 17:58
@alexviz7 I think I'm going to close this issue, things like handling multiple Cucumber tags are out of this plugin's scope. If you (or future readers) still have issues, you should try to handle multiple tags manually as you see fit, for example by writing custom feature file parsers/preprocessors: https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/86#issuecomment-1620794137

**Closed by csvtuda** 2023-08-28 17:58 UTC
Labels: feature, under investigation
