### ISSUE TITLE
Background steps included in Scenario without precondition tag, but fail shown

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#296] opened 2024-02-09 10:33 UTC
### Description

I updated the cypress xray plugin to the latest 6. I removed the merge background file that I had implemented for the 4th version.
The jira tickets show the results of the tagged scenario with the background steps (without a tag) which is what I wanted from the start.
But I get a fail when I run cypress which I think is a minor bug.
![Screenshot 2024-02-09 122427](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/e1cfbec3-a1c2-48e9-a504-32da4fa4c028)
![Screenshot 2024-02-09 123723](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/237e517c-d30c-499c-a3bb-2e6d5ac438a4)
![Screenshot 2024-02-09 123559](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/931ea200-1912-479a-946f-f24245fbe6d3)

### Cypress version

12.17.4

### Plugin version

6.0.0

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment] 2024-02-10 11:28
Hey @alexviz7,

if I understand your issue correctly, this is actually not a bug.

### Preface

> The jira tickets show the results of the tagged scenario with the background steps (without a tag)

Xray allows arbitrary results upload for tests of type Cucumber. This is why your step `Given user is on login page` appears in the performed steps in your screenshot, despite not being present in the scenario outline above.

For example, if you have the following scenario defined in Xray test `CYP-123`:

```gherkin
Given 5
When plus 6
Then 11
```

And let's say your corresponding Cypress feature file looks like this:

```gherkin
Feature: Modified upload

    @TestName:CYP-123
    Scenario: Modified upload test
        Given I like apples
        When I buy an orange
        When I buy a pineapple
        When I buy a pear
        Then I am sad
```

Then you can easily upload the results to the existing test, ending up with totally mismatched steps:

![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/9acb2f8f-47ce-4a5b-b04a-4232a14b0da5)


This behaviour is what previously allowed you to include your merged backgrounds in the result steps.

### What happened?

Since you've now removed the merging function, you've created the following situation:

1. the `cypress-xray-plugin` encounters a background element when trying to upload/sync the feature file
    - it scans the background for precondition tag comments, since without them, each background would result in a precondition issue being created on upload (in your case: [60 of them](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/86#issuecomment-1608945320))
    - it does not find any, skipping the upload with the error message in your screenshot
2. the `cypress-cucumber-preprocessor` executes your feature file
    - it creates the JSON report containing the executed steps
        - the report contains background steps as well as scenario steps
3. the `cypress-xray-plugin` uploads the JSON report to Xray
    - since Xray allows upload of mismatched steps, the results contain all steps present in the report (background & scenario steps)
4. you are left wondering why all the result steps are visible, yet the plugin refuses to upload/sync the feature file

### What can you do?

There's not much I can do to help you, since you're not structuring your feature files/Xray preconditions & tests like Xray tells users to do. The plugin is limited by the API Xray provides, which always creates precondition issues for unknown backgrounds on feature file upload/sync (unless tagged with a precondition issue comment).

Therefore, as far as I can see, your options are:

- start merging backgrounds into scenarios again to prevent the plugin from encountering untagged backgrounds
- start using precondition issues in Xray and adapt your feature files to them (background tags)

**Comment by alexviz7** [comment] 2024-02-12 08:29
Hello thank you first of all for your thorough answer. I know I can use the merge background solution. The thing is in version 4 there was no other solution because then the background steps did not even show up in the test results of the test jira ticket. Now this issue has been solved out of coincidence I don't know.  If its a bug this mismatch I do not know either. But if the prefix is undefined why not hide the xray plugin error ? The other solution maybe is to keep the uploadFeautures false.

**Comment by csvtuda** [comment] 2024-02-12 18:22
> The thing is in version 4 there was no other solution

In version 6, there's unfortunately still no other solution, apart from setting `uploadFeautures` to `false` like you mentioned, which is probably not what you want to do.

> Now this issue has been solved out of coincidence I don't know

It was either coincidence or Xray did something on their part. I know I didn't do anything in that regard 🤔 

> But if the prefix is undefined why not hide the xray plugin error?

Mostly because (new) plugin users would then be left wondering why the feature file upload results in 400 Bad Request all the time (as discussed [here](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/275#issuecomment-1854742690)). They would not be able to properly tag their feature files without the plugin explicitly telling them what to do, i.e. adding the correct prefixes (`TestName:`, `Test:`, `Precondition:`, ...) to their background/scenario issue tags.

Omitting the check entirely is a dangerous idea as well. If I now take out the check and you run the plugin once more, you'll end up with 60+ new precondition issues, simply because Xray will be unable to link your backgrounds to existing precondition issues (because you don't have any tags telling Xray which preconditions you've implemented in the corresponding background).

I hope this clears it up a little better.

**Comment by alexviz7** [comment] 2024-02-13 15:49
Ok maybe in the future it can be solved in order to have the option of having test results with background steps without a precondition ticket.

**Closed** 2024-02-15 13:19 UTC
Labels: bug, awaiting feedback
